apiVersion: v1
kind: Service
metadata:
    name: "golangcluster-2e98"
    labels:
        app: "golangcluster-2e98"
spec:
    type: LoadBalancer
    ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: http
    selector:
        app: "golangcluster-2e98"